// <auto-generated />
using LocalBusiness.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LocalBusiness.Migrations
{
    [DbContext(typeof(LocalBusinessContext))]
    [Migration("20220819170135_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("LocalBusiness.Models.Business", b =>
                {
                    b.Property<int>("BusinessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10) CHARACTER SET utf8mb4");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("BusinessId");

                    b.ToTable("Business");

                    b.HasData(
                        new
                        {
                            BusinessId = 1,
                            Address = "1 Technology Dr, Irvine, Ca 92618",
                            Name = "Pho Love",
                            Phone = "6267778888",
                            Type = "Restaurant"
                        },
                        new
                        {
                            BusinessId = 2,
                            Address = "123 Alton Parkway, Irvine, Ca 92618",
                            Name = "Four Sea Restaurant",
                            Phone = "4434425678",
                            Type = "Restaurant"
                        },
                        new
                        {
                            BusinessId = 3,
                            Address = "45 Jaboree Road, Irvine, Ca 92618",
                            Name = "Duke Bakery",
                            Phone = "8883332345",
                            Type = "Restaurant"
                        },
                        new
                        {
                            BusinessId = 4,
                            Address = "166 Alliance Ave, Tustin Ca 92780",
                            Name = "TjMax",
                            Phone = "9098885643",
                            Type = "Shop"
                        },
                        new
                        {
                            BusinessId = 5,
                            Address = "678 Tomson Street, Tustin Ca 92780",
                            Name = "Mayce",
                            Phone = "9092226789",
                            Type = "Shop"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
